### PR TITLE
Update topics-tester-list.md

### PR DESCRIPTION
**Pull request by markusze**
email updated for Magnite

### CODE REVIEW

**Comment by fabyf852-cell** [comment]
- ### _[
download

images
](url)_

**Comment by sumaakther833-bit** [comment]
Dear fabyf852-cell,

Thank you for your comment on the PR #263 regarding the topics-tester-list.md update. We appreciate your input! The changes are currently under review, and I will keep you informed of any further developments.

Best regards,
[Your Name]


-------- Original Email --------

**Comment by sumaakther833-bit** [comment]
Hello fabyf852-cell,

I noticed your comment regarding the topics-tester-list.md update. Could you please clarify your thoughts on the suggested changes? I'd like to fully understand the implications before moving forward.

Sincerely,
Pat


-------- Original Email --------

**Comment by sumaakther833-bit** [comment]
Yes it's I am

**Pull request merged**
